### PR TITLE
feat: add blacklist to getLocalesFromDir

### PR DESCRIPTION
**Pull request by rafaelramalho19**
When using the `lol` package inside webui's translation folder, it always added the `readme.md` file to the listing and had to be manually removed.

With this PR that doesn't happen anymore! And also added some cool tests 😎

### CODE REVIEW

**Review by lidel — APPROVED** [review]
LGTM, @olizilla mind reviewing and releasing in spare moment? :)

**Comment by olizilla** [comment]
How about filtering out anything that isn't a directory?

**Comment by rafaelramalho19** [comment]
You're right @olizilla it's simpler! Done 😄

**Review by lidel — APPROVED** [review]
lgtm – @olizilla ?

**Review by olizilla — APPROVED** [review]
✨ 🎷 🐩

**Comment by olizilla** [comment]
Thank you for the fix @rafaelramalho19! Now published as v2

```console
❖ ~/Code/olizilla/lol on master 
⨎ npm publish
+ @olizilla/lol@2.0.0
```

**Pull request merged**
